version: "3.9"


services:
  nginx:
    image: nginx:1.25
    ports: ["80:80"]
    depends_on: [server1, server2, server3, server4]
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro


  server1: &app
    build: ./backend
    environment:
      - REDIS_URL=redis://redis:6379/0
      - APP_PORT=8080
    expose: ["8080"]
    depends_on: [redis]


  server2:
    <<: *app


  server3:
    <<: *app


  server4:
    <<: *app


  redis:
    image: redis:7
    ports: ["6379:6379"]
    command: ["redis-server", "--save", "", "--appendonly", "no"]
